# Generated by Django 4.0.4 on 2022-05-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0003_contact_plan_plan_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_name',
            field=models.TextField(max_length=200),
        ),
    ]
