# Generated by Django 4.0.4 on 2022-05-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0004_alter_plan_plan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkscan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_date', models.DateField(auto_now_add=True)),
                ('nonerisa', models.IntegerField()),
                ('erisa', models.IntegerField()),
                ('cafeteria', models.IntegerField()),
                ('operating', models.IntegerField()),
            ],
        ),
    ]
