# Generated by Django 4.0.4 on 2022-05-20 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0005_checkscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField()),
            ],
        ),
    ]
