# Generated by Django 4.0.4 on 2022-05-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0007_player_guesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_guesses',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
