# Generated by Django 4.0.4 on 2022-05-20 01:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0008_player_guesses_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_guesses',
            name='scan_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
