# Generated by Django 4.0.4 on 2022-05-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0013_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='win',
            name='scan_date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
