# Generated by Django 4.0.4 on 2022-05-20 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0016_alter_player_guesses_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_guesses',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotteries.player', unique_for_date='scan_date'),
        ),
    ]
