# Generated by Django 4.0.4 on 2022-05-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0017_alter_player_guesses_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participating_Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participating_player', models.IntegerField()),
            ],
        ),
    ]
