# Generated by Django 4.0.4 on 2022-05-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0018_participating_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period_End_Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Period_End_Dates',
            },
        ),
        migrations.AlterModelOptions(
            name='participating_players',
            options={'verbose_name_plural': 'Participating_Players'},
        ),
    ]
