# Generated by Django 4.0.4 on 2022-05-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0019_period_end_dates_alter_participating_players_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkscan',
            name='scan_date',
        ),
    ]
