# Generated by Django 4.0.4 on 2022-05-29 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0020_remove_checkscan_scan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkscan',
            name='scan_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
