# Generated by Django 4.0.4 on 2022-05-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0021_checkscan_scan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkscan',
            name='scan_date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
