# Generated by Django 4.0.4 on 2022-06-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0023_alter_player_guesses_player'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='player_guesses',
            constraint=models.UniqueConstraint(fields=('player', 'scan_date'), name='unique_player_date_guess'),
        ),
    ]
