# Generated by Django 4.0.4 on 2022-06-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0024_player_guesses_unique_player_date_guess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_guesses',
            name='active',
        ),
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
