# Generated by Django 4.0.4 on 2022-07-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0025_remove_player_guesses_active_player_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_contact',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='plan_contact',
            name='plan',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Plan_Contact',
        ),
    ]
