# Generated by Django 4.0.4 on 2022-08-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0027_delete_entry_delete_topic'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player_guesses',
            name='unique_player_date_guess',
        ),
        migrations.AddConstraint(
            model_name='player_guesses',
            constraint=models.UniqueConstraint(fields=('player_id', 'scan_date'), name='unique_player_date_guess'),
        ),
    ]
