# Generated by Django 4.0.4 on 2022-11-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotteries', '0028_remove_player_guesses_unique_player_date_guess_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player_guesses',
            name='unique_player_date_guess',
        ),
        migrations.AddConstraint(
            model_name='player_guesses',
            constraint=models.UniqueConstraint(fields=('player', 'scan_date'), name='unique_player_date_guess'),
        ),
    ]
