# Generated by Django 4.1.3 on 2022-11-20 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0019_alter_incomedetail_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomedetail',
            name='type',
            field=models.CharField(choices=[('cash', 'cash'), ('card', 'card')], max_length=30),
        ),
        migrations.AlterField(
            model_name='stocking_history',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 3, 18, 52, 620733, tzinfo=datetime.timezone.utc)),
        ),
    ]
